[package]
name = "port-tester"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pt"
path = "src/main.rs"
test = false
doc = true

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
ctrlc = "3.5.1"
dns-lookup = "3.0.1"
hostname-validator = "1.1.1"
